#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../.. T_A=rhel8-x86_64-debug  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../.. T_A=rhel8-x86_64-debug  $@

force:  ;
